package ConcatModule;


/**
* ConcatModule/Concat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcatModule.idl
* Monday, 29 May, 2023 7:14:33 PM IST
*/

public interface Concat extends ConcatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concat
