package ConcatModule;


/**
* ConcatModule/ConcatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcatModule.idl
* Monday, 29 May, 2023 7:14:33 PM IST
*/

public interface ConcatOperations 
{
  String concat_string (String str1, String str2);
} // interface ConcatOperations
