package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Tuesday, 30 May, 2023 3:41:58 AM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
} // interface CalculatorOperations
